#FROM quay.io/centos-bootc/centos-bootc-dev:stream9
FROM quay.io/centos-bootc/fedora-bootc:eln

RUN dnf -y install vim python3 \
    python3-pip \
    python3-setuptools \
    python3-psycopg2 \
    nginx \
    postgresql-server \
    selinux-policy-devel \
&& rm /var/log/*.log /var/lib/dnf -rf

# Add the application user here, add another in the config.json
RUN useradd -ms /bin/bash cloud-user -G wheel
