FROM quay.io/centos-bootc/centos-bootc-dev:stream9

RUN dnf -y install python3 \
    python3-pip \
    python3-setuptools \
    python3-psycopg2 \
    nginx \
    postgresql-server \
    selinux-policy-devel \
&& rm /var/log/*.log /var/lib/dnf -rf

# Reuse the app user as the ansible user
RUN useradd -ms /bin/bash cloud-user -G wheel
# ADD core.conf /usr/lib/sysusers.d/

# This seems .. poor
ADD id_rsa_localvm.pub /var/home/cloud-user/.ssh/
RUN chmod 700 /var/home/cloud-user/.ssh && \
chmod 644 /var/home/cloud-user/.ssh/id_rsa_localvm.pub && \
chown -R cloud-user:cloud-user /var/home/cloud-user
