---
# tasks file for postgres

# Package install is now build time
#- name: Install postgres server
#  yum:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - postgresql-server
#    - python3-psycopg2

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ db_datapath }}"/PG_VERSION
  register: pgdata_dir_version

- name: Initialize PostgreSQL
  command: /usr/bin/postgresql-setup --initdb
  when: not pgdata_dir_version.stat.exists

- name: Update the authentication methods
  template:
    src: pg_hba.conf.j2
    dest: "{{ db_datapath }}"/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: Listen on all IPs
  lineinfile:
    dest: "{{ db_datapath }}"/postgresql.conf
    regexp: "^#listen_addresses"
    line: "listen_addresses = '*'"
    state: present
    backup: yes

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Ensure database is created
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    #lc_collate: 'en_US.UTF-8'
    #lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: Ensure user has access to the database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: yes
    priv: ALL
    state: present

- name: Ensure user does not have unnecessary privileges
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
